# Generated by Django 6.0.3 on 2026-04-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=512)),
                ('level', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=128)),
            ],
        ),
    ]
