# Generated by Django 6.0.3 on 2026-04-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_logevent_errorlogevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorLogEvent',
            new_name='LogEvent',
        ),
    ]
