# Generated by Django 6.0.3 on 2026-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_errorcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorcount',
            old_name='last_updated',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='errorcount',
            name='service',
            field=models.CharField(max_length=128),
        ),
    ]
