/*
 * This source file was generated by the Gradle 'init' task
 */
package org.logger;

import java.time.Duration;
import java.util.Properties;

import org.apache.kafka.common.serialization.StringSerializer;
import org.apache.kafka.common.serialization.ByteArraySerializer;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.messages.LogMessageSerde;
import org.messages.Message;
import org.streaming.ErrorFilteringStream;
import org.streaming.ErrorCountsStream;

public class App {
    public Properties createProperties() {
        Properties props = new Properties();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, System.getenv("KAFKA_BOOTSTRAP_SERVERS"));
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class);

        return props;
    }

    public Properties createStreamProperties() {
        Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "logs-stream-app");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, System.getenv("KAFKA_BOOTSTRAP_SERVERS"));
        props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.StringSerde.class);
        props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, LogMessageSerde.class);

        props.put(StreamsConfig.STATESTORE_CACHE_MAX_BYTES_CONFIG, 0);
        props.put(StreamsConfig.COMMIT_INTERVAL_MS_CONFIG, 100);

        return props;
    }

    public static void main(String[] args) {
        App app = new App();
        Properties props = app.createProperties();
        Properties streamProps = app.createStreamProperties();
        String rawLogsTopic = "raw-logs";

        StreamsBuilder builder = new StreamsBuilder();
        ErrorFilteringStream.build(builder, rawLogsTopic, "error-logs");
        ErrorCountsStream.build(builder, "error-logs", "error-counts");

        try (
            KafkaLogProducer producer = new KafkaLogProducer(props, rawLogsTopic);
            KafkaStreams streams = new KafkaStreams(builder.build(), streamProps);
        ) {
            streams.start();
            while (true) {
                Message message = LogGenerator.generateRandomMessage();
                System.out.println(message);
                producer.sendMessage(message);
                Thread.sleep(1000);
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}
