/*
 * This source file was generated by the Gradle 'init' task
 */
package org.logger;

import java.util.Arrays;
import java.util.List;
import java.util.Properties;

import org.apache.kafka.common.serialization.StringSerializer;
import org.apache.kafka.common.serialization.ByteArraySerializer;

import org.messages.Message;

public class App {
    public Properties createProperties() {
        Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("key.serializer", StringSerializer.class);
        props.put("value.serializer", ByteArraySerializer.class);

        return props;
    }

    public static void main(String[] args) {
        Properties props = new App().createProperties();
        String topic = "raw-logs";

        try (KafkaLogProducer producer = new KafkaLogProducer(props, topic)) {
            while (true) {
                Message message = LogGenerator.generateRandomMessage();
                System.out.println(message);
                producer.sendMessage(message);
                Thread.sleep(5000);
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
