/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val avroTools by configurations.creating

dependencies {
    // Source: https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients
    implementation("org.apache.kafka:kafka-clients:4.2.0")
    implementation("org.apache.kafka:kafka-streams:4.2.0")
    implementation("org.apache.avro:avro:1.12.0")
    avroTools("org.apache.avro:avro-tools:1.12.0")
    implementation("io.confluent:kafka-avro-serializer:8.2.0")
    implementation("io.confluent:kafka-streams-avro-serde:8.2.0")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.logger.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register<JavaExec>("generateAvroJava") {
    group = "build"
    description = "Generate Java classes from Avro schemas"

    classpath = avroTools
    mainClass.set("org.apache.avro.tool.Main")

    args(
        "compile",
        "schema",
        "$projectDir/src/main/avro/Message.avsc",
        "$projectDir/src/main/java"
    )
}